acciones/urls.py
from django.urls import path, include
from .views import Index, Crear_Accionista, Mostrar_temp, generar_pdf, guardar, Buscar_Accionista
from .views import Mostrar_temp_1

app_name = 'acciones'

urlpatterns =[
    path('index/', Index.as_view(), name='index'),
    path('nuevo/', Crear_Accionista.as_view(), name='nuevo'),
    path('mostrar_temp/', Mostrar_temp.as_view(), name='mostrar_temp'),
    path('imprimir/' ,generar_pdf.as_view(),name= 'imprimir'),
    path('guardar/', guardar, name='guardar'),
    path('buscar/,', Buscar_Accionista.as_view(), name='buscar',),
    path('mostrar_temp_1/', Mostrar_temp_1.as_view(), name='mostrar_temp_1'),
]

caja/urls.py
from django.urls import path, include
from .views import Index, Nuevo_Accion, Mostrar_Caja, Filtrar_Caja

app_name = 'caja'
urlpatterns = [
    path('index/', Index.as_view(), name='index'),
    path('nuevo/', Nuevo_Accion.as_view(), name='nuevo'),
    path('mostrar/', Mostrar_Caja.as_view(), name='mostrar'),
    path('filtrar/', Filtrar_Caja.as_view(), name='filtrar'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import HomeView
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('usuarios.urls', namespace='usuarios')),
    path('prestamos/', include('prestamos.urls', namespace='prestamos')),
    path('ahorros/', include('ahorros.urls', namespace='ahorros')),
    path('acciones/', include('acciones.urls',namespace='acciones')),
    path('caja/', include('caja.urls',namespace='caja')),
    path('inventario/', include('inventario.urls', namespace="inventario")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

acciones/models.py
from django.db import models

# Create your models here.
class Datos_Accionista(models.Model):
    Nombre= models.CharField(max_length=50)
    Identidad = models.CharField(max_length=15)
    Fecha_Ingreso = models.DateField()
    Fundador = models.CharField(max_length=1)

class Temp_Datos_Accionista(models.Model):
    Usuario = models.CharField(max_length=50)
    Nombre = models.CharField(max_length=50)
    Identidad = models.CharField(max_length=15)
    Fecha_Ingreso = models.DateField()
    Fundador = models.CharField(max_length=1)

class Acciones_accionista(models.Model):
    Fecha = models.DateField()
    Identidad = models.CharField(max_length=15)
    Num_Recibo= models.IntegerField()
    Reglamento = models.FloatField()
    Extaordinaria = models.FloatField()
    Utilidad = models.FloatField()
    Donación = models.FloatField()
    Intereses = models.FloatField()
    Perdidas = models.FloatField()
    Total = models.FloatField()

class Temp_Acciones_accionista(models.Model):
    Usuario = models.CharField(max_length=50)
    Identidad = models.CharField(max_length=15)
    Fecha = models.DateField()
    Num_Recibo = models.IntegerField()
    Reglamento = models.FloatField()
    Extaordinaria = models.FloatField()
    Utilidad = models.FloatField()
    Donación = models.FloatField()
    Intereses = models.FloatField()
    Perdidas = models.FloatField()
    Total = models.FloatField()

acciones/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import  TemplateView, ListView, View
from django.contrib import messages
from datetime import date
from .utils import render_to_pdf
from .models import Acciones_accionista, Datos_Accionista, Temp_Acciones_accionista, Temp_Datos_Accionista
from core.models import Libro_Diario, Libro_Mayor
from caja.models import Caja
# Create your views here.

class Index(TemplateView):
    template_name = "acciones/Index.html"

class Crear_Accionista(TemplateView):
    template_name = "acciones/Nuevo_Accionista.html"

    def validar_datos(self,request):
        id = request.POST['Identidad']
        if len(id) != 13:
            messages.error(request, "Error en Identidad", "Debe medir 13")
            return False
        list= Datos_Accionista.objects.filter(Identidad=id).count()
        if list>0:
            messages.error(request, "Ya existe un accionista con esa identidad", "Ya existe")
            return  False
        return  True

    def post(self, request, *args, **kwargs):
        va = self.validar_datos(request)
        if va == False:

            return render(request, "acciones/Nuevo_Accionista.html")
        else:
            Temp_Datos_Accionista.objects.filter(Usuario=request.user.username).delete()
            Temp_Acciones_accionista.objects.filter(Usuario=request.user.username).delete()
            A1 = Temp_Datos_Accionista(
                Nombre= request.POST['Cliente'],
                Identidad=request.POST['Identidad'],
                Fecha_Ingreso=request.POST['Fecha Ingreso'],
                Fundador=request.POST['Fundador'],
                Usuario= request.user.username

            )
            A1.save()

            Tipo_Accion = request.POST['Tipo_Apo']

            if Tipo_Accion=="reglamento":
                A2 = Temp_Acciones_accionista(
                    Usuario= request.user.username,
                    Fecha= date.today(),
                    Num_Recibo=int(request.POST['Núm. Recibo']),
                    Identidad= request.POST['Identidad'],
                    Reglamento= float(request.POST['Déposito Inicial']),
                    Extaordinaria=0.0,
                    Utilidad=0.0,
                    Donación=0.0,
                    Intereses=0.0,
                    Perdidas=0.0,
                    Total=float(request.POST['Déposito Inicial'])
                )
                A2.save()
            if Tipo_Accion=="donación":
                A2 = Temp_Acciones_accionista(
                    Usuario= request.user.username,
                    Fecha= date.today(),
                    Num_Recibo=int(request.POST['Núm. Recibo']),
                    Identidad= request.POST['Identidad'],
                    Reglamento= 0.0,
                    Extaordinaria=0.0,
                    Utilidad=0.0,
                    Donación=float(request.POST['Déposito Inicial']),
                    Intereses=0.0,
                    Perdidas=0.0,
                    Total=float(request.POST['Déposito Inicial'])
                )
                A2.save()

            if Tipo_Accion=="extraordinaria":
                A2 = Temp_Acciones_accionista(
                    Usuario= request.user.username,
                    Fecha= date.today(),
                    Num_Recibo=int(request.POST['Núm. Recibo']),
                    Identidad= request.POST['Identidad'],
                    Reglamento= 0.0,
                    Extaordinaria=float(request.POST['Déposito Inicial']),
                    Utilidad=0.0,
                    Donación=0.0,
                    Intereses=0.0,
                    Perdidas=0.0,
                    Total=float(request.POST['Déposito Inicial'])
                )
                A2.save()

        return redirect("acciones:mostrar_temp")

class Mostrar_temp(ListView):
    template_name ="acciones/Accionista_Mostrar.html"
    model = Temp_Acciones_accionista


    def get_context_data(self, *, object_list=None, **kwargs):
        ctx =super().get_context_data()
        datos = Temp_Datos_Accionista.objects.get(Usuario=self.request.user.username)

        ctx.update({
            'Cliente': datos.Nombre,
            'Identidad': datos.Identidad,
            'Fecha_Ingreso': datos.Fecha_Ingreso,
            'Fundador': datos.Fundador
        })
        return ctx
    def get_queryset(self):
        return Temp_Acciones_accionista.objects.filter(Usuario=self.request.user.username)

class generar_pdf(View):
    def get(self, request, *args, **kwargs):
        ob = Temp_Acciones_accionista.objects.filter(Usuario=request.user.username)
        presta = Temp_Datos_Accionista.objects.get(Usuario=request.user.username)

        ctx = {
            'Cliente': presta.Nombre,
            'Identidad': presta.Identidad,
            'Fecha_Ingreso': presta.Fecha_Ingreso,
            'Fundador': presta.Fundador,
            'object_list': ob
        }
        pdf= render_to_pdf('pdf/acciones_mostrar.html',ctx)
        if pdf:
            response = HttpResponse(pdf, content_type='acciones/pdf')
            filename = "Aportaciones_%s.pdf" % (presta.Nombre)
            content = "inline; filename=%s" % (filename)
            download = request.GET.get("download")
            if download:
                content = "attachment; filename=%s" % (filename)
            response['Content-Disposition'] = content
            return response
        return HttpResponse("Not found")




def guardar(request):
    datos_accionista = Temp_Datos_Accionista.objects.get(Usuario=request.user.username)
    acciones_accionista= Temp_Acciones_accionista.objects.get(Usuario=request.user.username)
    Nombre = datos_accionista.Nombre
    A1 = Datos_Accionista(
        Nombre= datos_accionista.Nombre,
        Identidad=datos_accionista.Identidad,
        Fecha_Ingreso=datos_accionista.Fecha_Ingreso,
        Fundador=datos_accionista.Fundador
    )
    A1.save()

    A2 = Acciones_accionista(
        Fecha= acciones_accionista.Fecha,
        Identidad=acciones_accionista.Identidad,
        Num_Recibo=acciones_accionista.Num_Recibo,
        Reglamento=acciones_accionista.Reglamento,
        Extaordinaria=acciones_accionista.Extaordinaria,
        Utilidad=acciones_accionista.Utilidad,
        Donación=acciones_accionista.Donación,
        Intereses=acciones_accionista.Intereses,
        Perdidas=acciones_accionista.Perdidas,
        Total=acciones_accionista.Total,
    )

    A2.save()
    cantidad_movimiento = acciones_accionista.Reglamento+ acciones_accionista.Extaordinaria+ acciones_accionista.Utilidad
    cantidad_movimiento =cantidad_movimiento+ acciones_accionista.Donación
    M1 = Libro_Diario(
        Usuario=request.user.username,
        Fecha=date.today(),
        Descripcion="Depósito Aportaciones: "+ Nombre,
        Debe= "Caja: +" + str(cantidad_movimiento),
        Haber="Aportaciones_Miembros: -" + str(cantidad_movimiento),
        Cuadre=0.0
    )
    M1.save()
    c = Libro_Mayor.objects.filter(Cuenta="Aportaciones_Miembros").count()
    if c==0:
        M2 = Libro_Mayor(
            Cuenta="Aportaciones_Miembros",
            Debe=0.0,
            Haber=cantidad_movimiento,
            Fecha=date.today(),
            Cuadre=-cantidad_movimiento,
            Descripcion="Depósito Aportaciones: "+ Nombre
        )
        M2.save()
    else:
        cuadre = Libro_Mayor.objects.filter(Cuenta="Aportaciones_Miembros").last().Cuadre
        M2 = Libro_Mayor(
            Cuenta="Aportaciones_Miembros",
            Debe=0.0,
            Haber=cantidad_movimiento,
            Fecha=date.today(),
            Cuadre=cuadre-cantidad_movimiento,
            Descripcion="Depósito Aportaciones: " + Nombre
        )
        M2.save()
    cuadre_caja=0.0
    c = Libro_Mayor.objects.filter(Cuenta="Caja").count()
    if c>0:
        cuadre_caja= Libro_Mayor.objects.filter(Cuenta="Caja").last().Cuadre
    M3 = Libro_Mayor(
        Cuenta="Caja",
        Debe=cantidad_movimiento,
        Haber=0.0,
        Cuadre=cuadre_caja+cantidad_movimiento,
        Fecha=date.today(),
        Descripcion="Depósito Aportaciones: " + Nombre


    )
    M3.save()
    M4 = Caja(
        Fecha=date.today(),
        Num_Recibo=acciones_accionista.Num_Recibo,
        Descripción="Depósito Aportaciones: " + Nombre,
        Entrada=cantidad_movimiento,
        Salida=0.0,
        Saldo=cuadre_caja+cantidad_movimiento,
    )
    M4.save()

    Temp_Acciones_accionista.objects.filter(Usuario=request.user.username).delete()
    Temp_Datos_Accionista.objects.filter(Usuario=request.user.username).delete()

    return redirect("usuarios:Libro Diario")

class Buscar_Accionista(TemplateView):
    template_name = "acciones/Buscar Accionista.html"

    def  post(self, request, *args, **kwargs):
        id = request.POST['Identidad']
        accionistas = Datos_Accionista.objects.filter(Identidad=id)
        if accionistas.count() ==0 :
            messages.error(request,"No existe accionista con esa id", 'erro de id')
            return  render(request,"acciones/Buscar Accionista.html")
        else:
            datos_accionista = Datos_Accionista.objects.get(Identidad=id)
            acciones_accionista = Acciones_accionista.objects.filter(Identidad=id)

            Temp_Acciones_accionista.objects.filter(Usuario= request.user.username).delete()
            Temp_Datos_Accionista.objects.filter(Usuario=request.user.username).delete()

            A1 = Temp_Datos_Accionista(
                Usuario= request.user.username,
                Nombre= datos_accionista.Nombre,
                Identidad=datos_accionista.Identidad,
                Fecha_Ingreso=datos_accionista.Fecha_Ingreso,
                Fundador=datos_accionista.Fundador
            )
            A1.save()
            for accion in acciones_accionista:
                A2 = Temp_Acciones_accionista(
                    Usuario= request.user.username,

templates/acciones/Accionista_Mostrar.html
{% extends 'core/base.html' %}

{% block head_title %}Aportante{% endblock %}



{% block content %}
    <h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10">Miembro</h1>
    <hr />

        <div class="mb-4">
            <label class="block text-gray-700 text-sm " for="amount">
                <b>Cliente</b>: {{Cliente}}
            </label>
            <label class="block text-gray-700 text-sm" for="amount">
                <b>Identidad</b>: {{ Identidad }}
            </label>
            <label class="block text-gray-700 text-sm" for="amount">
                <b>Fecha de Ingreso</b>: {{ Fecha_Ingreso }}
            </label>

            <label class="block text-gray-700 text-sm" for="amount">
                <b>Miembro Fundador</b>: {{ Fundador }}
            </label>

        </div>
        {% if messages %}
            <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
         <a href="{% url 'acciones:imprimir' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Imprimir
         </a>
        <a href="{% url 'acciones:guardar' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Guardar
         </a>
        <button onclick="Atrás()" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Atrás</button>
        <script>
        function Atrás() {
            window.history.back();
        }
</script>
    <table class="table-auto mx-auto w-full mt-8">
        <thead class="bg-gray-800 text-white">
        <tr class="uppercase font-semibold text-sm">
            <th class="px-4 py-2">Fecha</th>
            <th class="px-4 py-2">Núm. Recibo</th>
            <th class="px-4 py-2">Aportación por reglamento</th>
            <th class="px-4 py-2">Aportación extraordinaria</th>
            <th class="px-4 py-2">Aportación por utilidad</th>
            <th class="px-4 py-2">Aportación por donación</th>
            <th class="px-4 py-2">Aportaciones por intereses</th>
            <th class="px-4 py-2">Reducción</th>
            <th class="px-4 py-2">Total</th>

        </tr>
        </thead>
        <tbody>
        {% for transaction in object_list %}
        <tr class="{% cycle 'bg-gray-300' 'bg-white-100' %}">
            <td class="border px-4 py-2 text-center">{{ transaction.Fecha }}</td>
            <td class="border px-4 py-2 text-center">{{ transaction.Num_Recibo }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Reglamento }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Extaordinaria }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.ReUtilidadtiro }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Donación }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Intereses }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Perdidas }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Total }}</td>

        </tr>
        {% endfor %}

        </tbody>
    </table>
{% endblock %}

templates/acciones/Accionista_mostrar_pago.html
{% extends 'core/base.html' %}

{% block head_title %}Aportante{% endblock %}



{% block content %}
    <h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10">Aportante</h1>
    <hr />

        <div class="mb-4">
            <label class="block text-gray-700 text-sm" for="amount">
                <b>Cliente</b>: {{Cliente}}
            </label>
            <label class="block text-gray-700 text-sm" for="amount">
                <b>Identidad</b>: {{ Identidad }}
            </label>
            <label class="block text-gray-700 text-sm" for="amount">
                <b>Fecha de Ingreso</b>: {{ Fecha_Ingreso }}
            </label>

            <label class="block text-gray-700 text-sm" for="amount">
                <b>Miembro Fundador</b>: {{ Fundador }}
            </label>

        </div>
        {% if messages %}
            <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
         <a href="{% url 'acciones:imprimir' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Imprimir
         </a>
        <form method="POST" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}

        <div class="mb-4">
             <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                Cantidad
            </label>
            </label>
            <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="Cantidad" id="Cantidad"  required placeholder="Cantidad ">
            <select name="Tipo_Apo" id="Tipo_Apo"class="border rounded text-black border-red-900 hover:block mt-4 lg:inline-block lg:mt-0 text-black hover:text-red mr-4">>
                <option value="reglamento">Aportación por reglamento</option>
                <option value="donación">Aportación por donación</option>
                <option value="extraordinaria">Aportación extraordinaria</option>
                <option value="reduccion">Retirar</option>
            </select>
            <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                Num_Recibo
            </label>
             <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="Num_Recibo" id="Num_Recibo"  required placeholder="Num_Recibo ">
            </select>
        </div>

        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
            Ejecutar
        </button>
    </form>
    <table class="table-auto mx-auto w-full mt-8">
        <thead class="bg-gray-800 text-white">
        <tr class="uppercase font-semibold text-sm">
            <th class="px-4 py-2">Fecha</th>
            <th class="px-4 py-2">Núm. Recibo</th>
            <th class="px-4 py-2">Aportación por reglamento</th>
            <th class="px-4 py-2">Aportación extraordinaria</th>
            <th class="px-4 py-2">Aportación por utilidad</th>
            <th class="px-4 py-2">Aportación por donación</th>
            <th class="px-4 py-2">Aportaciones por intereses</th>
            <th class="px-4 py-2">Reducción </th>
            <th class="px-4 py-2">Total</th>

        </tr>
        </thead>
        <tbody>
        {% for transaction in object_list %}
        <tr class="{% cycle 'bg-gray-300' 'bg-white-100' %}">
            <td class="border px-4 py-2 text-center">{{ transaction.Fecha }}</td>
            <td class="border px-4 py-2 text-center">{{ transaction.Num_Recibo }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Reglamento }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Extaordinaria }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.ReUtilidadtiro }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Donación }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Intereses }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Perdidas }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Total }}</td>

        </tr>
        {% endfor %}

        </tbody>
    </table>
{% endblock %}

templates/acciones/Buscar Accionista.html
{% extends 'core/base.html' %}

{% block head_title %}Aportador{% endblock %}



{% block content %}
    <h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10">Buscar  Aportante</h1>
    <hr />
    <form method="POST" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}

        <div class="mb-4">
             <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                Identidad
            </label>
            <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="Identidad" id="Identidad"  required placeholder="Identidad del Cliente">
        </div>
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
            Buscar
        </button>
    </form>

{% endblock %}

templates/acciones/Index.html
{% extends 'core/base.html' %}

{% block head_title %}Aportaciones{% endblock %}



{% block content %}
    <h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10"> Aportaciones </h1>
    <hr />
<center>
   <a href="{% url 'acciones:nuevo' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Nuevo
   </a>
    <a href="{% url 'acciones:buscar' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Existente
   </a>
</center>
{% endblock %}

templates/acciones/Nuevo_Accionista.html
{% extends 'core/base.html' %}

{% block head_title %}Nuevo Aportador{% endblock %}



{% block content %}
    <h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10">Nuevo Aportante</h1>
    <hr />
    <form method="POST" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}

        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                Cliente
            </label>
            <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="Cliente" id="Cliente"  required placeholder="Nombre del Cliente">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                Identidad
            </label>
            <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="Identidad" id="Identidad"  required placeholder="Identidad del Cliente">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                Fecha_Ingreso
            </label>
             <input type="Date" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="Fecha Ingreso" id="Fecha Ingreso"  required value=today>
            <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                Miembro Fundador
            </label>

            <select name="Fundador" id="Fundador">
                 <option value="S">S</option>
                 <option value="N">N</option>
            </select>

            <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                Aportación Inicial
            </label>

            <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="Déposito Inicial" id="Déposito Inicial"  required placeholder="Déposito Inicial">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                Tipo de Aportación Inicial
            </label>
            <select name="Tipo_Apo" id="Tipo_Apo">
                 <option value="reglamento">Aportación por reglamento</option>
                 <option value="donación">Aportación por donación</option>
                 <option value="extraordinaria">Aportación extraordinaria</option>

            </select>
            <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                Núm. Recibo
            </label>
            <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="Núm. Recibo" id="Núm. Recibo"  required placeholder="Núm. Recibo">
        </div>
        {% if messages %}
            <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
            Crear
        </button>
    </form>

{% endblock %}