ahorros/urls.py
from django.urls import path, include
from .views import Index, Crear_Cuenta, Mostrar_Temp, generar_pdf, Buscar_Ahorrante, guardar
from .views import Mostrar_Temp_1
app_name = 'ahorros'
urlpatterns = [
    path('index/',Index.as_view(), name='index'),
    path('nuevo',Crear_Cuenta.as_view(), name='nuevo'),
    path('mostrar_temp/',Mostrar_Temp.as_view(),name='mostrar_temp'),
    path('imprimir/', generar_pdf.as_view(),name='imprimir'),
    path('guardar/',guardar, name ='guardar'),
    path('buscar/', Buscar_Ahorrante.as_view(), name= 'buscar' ),
    path('mostrar_temp_1/',Mostrar_Temp_1.as_view(),name='mostrar_temp_1'),
]

caja/urls.py
from django.urls import path, include
from .views import Index, Nuevo_Accion, Mostrar_Caja, Filtrar_Caja

app_name = 'caja'
urlpatterns = [
    path('index/', Index.as_view(), name='index'),
    path('nuevo/', Nuevo_Accion.as_view(), name='nuevo'),
    path('mostrar/', Mostrar_Caja.as_view(), name='mostrar'),
    path('filtrar/', Filtrar_Caja.as_view(), name='filtrar'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import HomeView
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('usuarios.urls', namespace='usuarios')),
    path('prestamos/', include('prestamos.urls', namespace='prestamos')),
    path('ahorros/', include('ahorros.urls', namespace='ahorros')),
    path('acciones/', include('acciones.urls',namespace='acciones')),
    path('caja/', include('caja.urls',namespace='caja')),
    path('inventario/', include('inventario.urls', namespace="inventario")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ahorros/models.py
from django.db import models

# Create your models here.

class Datos_Ahorros(models.Model):
    Identidad = models.CharField(max_length=15)
    Nombre =  models.CharField(max_length=50)
    Beneficiarios= models.CharField(max_length=100)
    Observacions = models.CharField(max_length=100)

class Acciones_Ahorros(models.Model):
    Identidad = models.CharField(max_length=15)
    Fecha = models.DateField()
    Num_Recibo = models.IntegerField()
    Deposito= models.FloatField()
    Intereses = models.FloatField()
    Retiro = models.FloatField()
    Saldo = models.FloatField()

class Temp_Datos_Ahorrante(models.Model):
    usuario = models.CharField(max_length=30)
    Identidad = models.CharField(max_length=15)
    Nombre = models.CharField(max_length=50)
    Beneficiarios = models.CharField(max_length=100)
    Observacions = models.CharField(max_length=100)

class Temp_Datos_Acciones_Ahorro(models.Model):
    Identidad = models.CharField(max_length=15)
    usuario = models.CharField(max_length=30)
    Fecha = models.DateField()
    Num_Recibo = models.IntegerField()
    Deposito = models.FloatField()
    Intereses = models.FloatField()
    Retiro = models.FloatField()
    Saldo = models.FloatField()

ahorros/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import  TemplateView, ListView
from django.contrib import messages
from datetime import date
from django.views import View
from .models import  Temp_Datos_Ahorrante, Temp_Datos_Acciones_Ahorro, Acciones_Ahorros, Datos_Ahorros
from .utils import render_to_pdf
from core.models import Libro_Diario, Libro_Mayor
from caja.models import Caja
# Create your views here.

class Index(TemplateView):
    template_name= "ahorros/Index.html"


class Crear_Cuenta (TemplateView):
    template_name = "ahorros/Nuevo_Ahorrante.html"

    def validar_datos(self, request):
        identidad =  request.POST['Identidad']
        if len(identidad) != 13:
            messages.error(request, "Error en Identidad", "Debe medir 13")
            return False
        dep_inicial= request.POST['Déposito Inicial']
        dep_inicial= str(dep_inicial)
        if dep_inicial.isdigit():
            dep = float(request.POST['Déposito Inicial'])
            if dep <= 0:
                messages.error(request, "Error en Déposito Inicial", "Debe medir 13")
                return False
        else:
            messages.error(request, "Error en Déposito Inicial", "Debe medir 13")
            return False
        c= Datos_Ahorros.objects.filter(Identidad=identidad).count()
        if c>0:
            messages.error(request,"Ahorrante ya existe", "Ya existe")
            return False
        return True

    def post(self, request, *args, **kwargs):
        va = self.validar_datos(request)
        if va == False:
            c = {
                'Cliente': request.POST['Cliente'],
                'Identidad': request.POST['Identidad'],
                'Beneficiarios': request.POST['Beneficiarios'],
                'Observaciones': request.POST['Observaciones'],
                'Déposito Inicial': request.POST['Déposito Inicial']
            }
            return  render(request, "ahorros/Nuevo_Ahorrante.html",context=c)
        else:
            user= request.user.username
            Temp_Datos_Ahorrante.objects.filter(usuario=user).delete()
            Temp_Datos_Acciones_Ahorro.objects.filter(usuario=user).delete()
            A1 = Temp_Datos_Ahorrante(
                Identidad=request.POST['Identidad'],
                Nombre= request.POST['Cliente'],
                usuario=user,
                Beneficiarios= request.POST['Beneficiarios'],
                Observacions=request.POST['Observaciones'],

            )
            A1.save()
            A2 = Temp_Datos_Acciones_Ahorro(
                    Fecha= date.today(),
                    usuario=request.user.username,
                    Identidad= request.POST['Identidad'],
                    Num_Recibo=request.POST['Núm. Recibo'],
                    Deposito= float(request.POST['Déposito Inicial']),
                    Intereses= 0.0,
                    Retiro= 0.0,
                    Saldo= float(request.POST['Déposito Inicial']),

            )
            A2.save()

            return  redirect('ahorros:mostrar_temp')



class Mostrar_Temp(ListView):
    template_name = "ahorros/Ahorrante_mostrar.html"
    model = Temp_Datos_Acciones_Ahorro
    def get_context_data(self, *, object_list=None, **kwargs):
        ctx = super().get_context_data(**kwargs)
        info = Temp_Datos_Ahorrante.objects.filter(usuario= self.request.user.username)
        pres = info[0]
        ctx.update({
            'Cliente': pres.Nombre,
            'Identidad': pres.Identidad,
            'Beneficiarios': pres.Beneficiarios,
            'Observaciones': pres.Observacions,
        })

        return ctx
    def get_queryset(self):
        user = self.request.user.username
        return  Temp_Datos_Acciones_Ahorro.objects.filter(usuario=user)


class generar_pdf(View):
    def get(self, request, *args, **kwargs):
        ob = Temp_Datos_Acciones_Ahorro.objects.filter(usuario=request.user.username)
        presta= Temp_Datos_Ahorrante.objects.filter(usuario=request.user.username)
        dato= presta[0]
        ctx = {
            'Cliente': dato.Nombre,
            'Identidad': dato.Identidad,
            'Beneficiarios': dato.Beneficiarios,
            'Observaciones': dato.Observacions,
            'object_list': ob
        }
        pdf= render_to_pdf('pdf/ahorros_mostrar.html',ctx)
        if pdf:
            response = HttpResponse(pdf, content_type='ahorros/pdf')
            filename = "Ahorros_%s.pdf" % (dato.Nombre)
            content = "inline; filename=%s" % (filename)
            download = request.GET.get("download")
            if download:
                content = "attachment; filename=%s" % (filename)
            response['Content-Disposition'] = content
            return response
        return HttpResponse("Not found")


def guardar(request):
     datos = Temp_Datos_Ahorrante.objects.get(usuario=request.user.username)
     acciones = Temp_Datos_Acciones_Ahorro.objects.filter(usuario=request.user.username)
     Nombre = datos.Nombre
     A1 = Datos_Ahorros(
       Identidad= datos.Identidad,
       Nombre= datos.Nombre,
       Beneficiarios= datos.Beneficiarios,
       Observacions= datos.Observacions,
     )
     A1.save()

     for accion in acciones:
         A2 = Acciones_Ahorros(
             Identidad= accion.Identidad,
             Fecha= accion.Fecha,
             Num_Recibo=accion.Num_Recibo,
             Deposito= accion.Deposito,
             Intereses=accion.Intereses,
             Retiro=accion.Retiro,
             Saldo=accion.Saldo,
         )
         A2.save()

     if accion.Deposito ==0:
         M1 = Libro_Diario(
             Usuario=request.user.username,
             Fecha=date.today(),
             Descripcion= "Retiro de "+ Nombre,
             Debe= "Capital_e_intereses_en_ahorros +" + str(accion.Retiro),
             Haber= "Caja -" + str(accion.Retiro),
             Cuadre= 0.0

         )
         M1.save()

         c = Libro_Mayor.objects.filter(Cuenta="Capital_e_intereses_en_ahorros").count()
         if c==0:
             M2 = Libro_Mayor(
                 Cuenta="Capital_e_intereses_en_ahorros",
                 Debe=float(accion.Retiro),
                 Haber=0.0,
                 Cuadre=-float(accion.Retiro),
                 Fecha=date.today(),
                 Descripcion="Retiro " + Nombre
             )
             M2.save()
         else:
            cuadre = Libro_Mayor.objects.filter(Cuenta="Capital_e_intereses_en_ahorros").last().Cuadre
            M2 = Libro_Mayor(
                Cuenta="Capital_e_intereses_en_ahorros",
                Debe=float(accion.Retiro),
                Haber=0.0,
                Cuadre=cuadre+float(accion.Retiro),
                Fecha=date.today(),
                Descripcion="Retiro " + Nombre
             )
            M2.save()
         saldo_caja=0.0
         c2 = Libro_Mayor.objects.filter(Cuenta="Caja").count()
         if c2>0:
             saldo_caja= Libro_Mayor.objects.filter(Cuenta="Caja").last().Cuadre

         M3 = Libro_Mayor(
             Cuenta="Caja",
             Debe=0.0,
             Haber=-accion.Retiro,
             Cuadre= saldo_caja-accion.Retiro,
             Fecha=date.today(),
             Descripcion="Retiro " + Nombre,
         )
         M3.save()
         M4 = Caja(
             Fecha=date.today(),
             Num_Recibo=accion.Num_Recibo,
             Descripción="Retiro " + Nombre,
             Entrada=0.0,
             Salida=accion.Retiro,
             Saldo=saldo_caja-accion.Retiro
         )
         M4.save()
     else:
         M1 = Libro_Diario(
             Usuario=request.user.username,
             Fecha=date.today(),
             Descripcion="Depósito Ahorros " + Nombre,
             Debe= "Caja +" + str(accion.Deposito),
             Haber="Capital_e_intereses_en_ahorros -" + str(accion.Deposito),
             Cuadre=0.0

         )
         M1.save()

         c = Libro_Mayor.objects.filter(Cuenta="Capital_e_intereses_en_ahorros").count()
         if c == 0:
             M2 = Libro_Mayor(
                 Cuenta="Capital_e_intereses_en_ahorros",
                 Debe=0.0,
                 Haber=float(accion.Deposito),
                 Cuadre=-float(accion.Deposito),
                 Fecha=date.today(),
                 Descripcion="Depósito Ahorros: " + Nombre,
             )
             M2.save()
         else:
             cuadre = Libro_Mayor.objects.filter(Cuenta="Capital_e_intereses_en_ahorros").last().Cuadre
             M2 = Libro_Mayor(
                 Cuenta="Capital_e_intereses_en_ahorros",
                 Debe=0.0,
                 Haber=float(accion.Deposito),
                 Cuadre=cuadre - float(accion.Deposito),
                 Fecha=date.today(),
                 Descripcion="Depósito Ahorros: " + Nombre,
             )
             M2.save()
         saldo_caja = 0.0
         c2 = Libro_Mayor.objects.filter(Cuenta="Caja").count()
         if c2 > 0:
             saldo_caja = Libro_Mayor.objects.filter(Cuenta="Caja").last().Cuadre

         M3 = Libro_Mayor(
             Cuenta="Caja",
             Debe=accion.Deposito,
             Haber=0.0,
             Cuadre=saldo_caja + accion.Deposito,
             Fecha=date.today(),
             Descripcion="Depósito Ahorros: " + Nombre,
         )
         M3.save()

     M4 = Caja(
         Fecha=date.today(),
         Num_Recibo=accion.Num_Recibo,
         Descripción="Depósito Ahorros: " + Nombre,
         Entrada=accion.Deposito,
         Salida=0.0,
         Saldo=saldo_caja + accion.Deposito
     )
     M4.save()

     return redirect("usuarios:Libro Diario")


class Buscar_Ahorrante(TemplateView):
    template_name = "ahorros/Buscar_ahorrante.html"

    def post(self, request, *args, **kwargs):
        Temp_Datos_Acciones_Ahorro.objects.filter(usuario=self.request.user.username).delete()
        Temp_Datos_Ahorrante.objects.filter(usuario=self.request.user.username).delete()

templates/ahorros/Ahorrante_mostrar.html
{% extends 'core/base.html' %}

{% block head_title %}Ahorrante{% endblock %}



{% block content %}
    <h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10">Ahorrante</h1>
    <hr />

        <div class="mb-4">
            <label class="block text-gray-700 text-sm" for="amount">
                <b>Cliente</b>: {{Cliente}}
            </label>
            <label class="block text-gray-700 text-sm" for="amount">
                <b>Identidad</b>: {{ Identidad }}
            </label>
            <label class="block text-gray-700 text-sm" for="amount">
                <b>Beneficiarios</b>: {{ Beneficiarios }}
            </label>

            <label class="block text-gray-700 text-sm" for="amount">
                <b>Observaciones</b>: {{ Observaciones }}
            </label>

        </div>
        {% if messages %}
            <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
         <a href="{% url 'ahorros:imprimir' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Imprimir
         </a>
        <a href="{% url 'ahorros:guardar' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Guardar
         </a>
         <button onclick="Atrás()" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Atrás</button>
        <script>
        function Atrás() {
            window.history.back();
        }
</script>
    <table class="table-auto mx-auto w-full mt-8">
        <thead class="bg-gray-800 text-white">
        <tr class="uppercase font-semibold text-sm">
            <th class="px-4 py-2">Fecha</th>
            <th class="px-4 py-2">Núm. Recibo</th>
            <th class="px-4 py-2">Deposito</th>
            <th class="px-4 py-2">Interes</th>
            <th class="px-4 py-2">Retiro</th>
            <th class="px-4 py-2">Saldo</th>

        </tr>
        </thead>
        <tbody>
        {% for transaction in object_list %}
        <tr class="{% cycle 'bg-gray-300' 'bg-white-100' %}">
            <td class="border px-4 py-2 text-center">{{ transaction.Fecha }}</td>
            <td class="border px-4 py-2 text-center">{{ transaction.Num_Recibo }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Deposito }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Intereses }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Retiro }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Saldo }}</td>

        </tr>
        {% endfor %}

        </tbody>
    </table>
{% endblock %}

templates/ahorros/Ahorrante_mostrar_pago.html
{% extends 'core/base.html' %}

{% block head_title %}Ahorrante{% endblock %}



{% block content %}
    <h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10">Ahorrante</h1>
    <hr />

        <div class="mb-4">
            <label class="block text-gray-700 text-sm" for="amount">
                <b>Cliente</b>: {{Cliente}}
            </label>
            <label class="block text-gray-700 text-sm" for="amount">
               <b> Identidad</b>: {{ Identidad }}
            </label>
            <label class="block text-gray-700 text-sm" for="amount">
                <b>Beneficiarios</b>: {{ Beneficiarios }}
            </label>

            <label class="block text-gray-700 text-sm" for="amount">
                <b>Observaciones</b>: {{ Observaciones }}
            </label>

        </div>
        {% if messages %}
            <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
        <form method="POST" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}

        <div class="mb-4">
             <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                Cantidad
            </label>
            <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="Cantidad" id="Cantidad"  required placeholder="Cantidad ">
            <select name="Accion" id="Accion">
                 <option value="Depositar">Depositar</option>
                 <option value="Retirar">Retirar</option>
            </select>
            <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                Num_Recibo
            </label>
             <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="Num_Recibo" id="Num_Recibo"  required placeholder="Num_Recibo ">
            </select>
        </div>

        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
            Ejecutar
        </button>
    </form>
         <a href="{% url 'ahorros:imprimir' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Imprimir
         </a>

    <table class="table-auto mx-auto w-full mt-8">
        <thead class="bg-gray-800 text-white">
        <tr class="uppercase font-semibold text-sm">
            <th class="px-4 py-2">Fecha</th>
            <th class="px-4 py-2">Núm. Recibo</th>
            <th class="px-4 py-2">Deposito</th>
            <th class="px-4 py-2">Interes</th>
            <th class="px-4 py-2">Retiro</th>
            <th class="px-4 py-2">Saldo</th>

        </tr>
        </thead>
        <tbody>
        {% for transaction in object_list %}
        <tr class="{% cycle 'bg-gray-300' 'bg-white-100' %}">
            <td class="border px-4 py-2 text-center">{{ transaction.Fecha }}</td>
            <td class="border px-4 py-2 text-center">{{ transaction.Num_Recibo }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Deposito }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Intereses }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Retiro }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Saldo }}</td>

        </tr>
        {% endfor %}

        </tbody>
    </table>
{% endblock %}

templates/ahorros/Buscar_ahorrante.html
{% extends 'core/base.html' %}

{% block head_title %}Ahorros{% endblock %}



{% block content %}
    <h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10">Buscar  Ahorrante</h1>
    <hr />
    <form method="POST" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}

        <div class="mb-4">
             <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                Identidad
            </label>
            <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="Identidad" id="Identidad"  required placeholder="Identidad del Cliente">
        </div>
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
            Buscar
        </button>
    </form>

{% endblock %}

templates/ahorros/Index.html
{% extends 'core/base.html' %}

{% block head_title %}Ahorros{% endblock %}



{% block content %}
    <h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10"> Ahorrante </h1>
    <hr />
<center>
   <a href="{% url 'ahorros:nuevo' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Nuevo
   </a>
    <a href="{% url 'ahorros:buscar' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Existente
   </a>
 </center>
{% endblock %}

templates/ahorros/Nuevo_Ahorrante.html
{% extends 'core/base.html' %}

{% block head_title %}Nuevo Ahorrante{% endblock %}



{% block content %}
    <h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10">Nuevo Ahorrante</h1>
    <hr />
    <form method="POST" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}

        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                Cliente
            </label>
            <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="Cliente" id="Cliente"  required placeholder="Nombre del Cliente">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                Identidad
            </label>
            <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="Identidad" id="Identidad"  required placeholder="Identidad del Cliente">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                Beneficiarios
            </label>
            <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="Beneficiarios" id="Beneficiarios"  required placeholder="Beneficiarios del Cliente">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                Observaciones
            </label>
            <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="Observaciones" id="Observaciones"  required placeholder="Observaciones del Cliente">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                Déposito Inicial
            </label>
            <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="Déposito Inicial" id="Déposito Inicial"  required placeholder="Déposito Inicial">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                Núm. Recibo
            </label>
            <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="Núm. Recibo" id="Núm. Recibo"  required placeholder="Núm. Recibo">
        </div>
        {% if messages %}
            <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
            Crear
        </button>
    </form>

{% endblock %}