caja/urls.py
from django.urls import path, include
from .views import Index, Nuevo_Accion, Mostrar_Caja, Filtrar_Caja

app_name = 'caja'
urlpatterns = [
    path('index/', Index.as_view(), name='index'),
    path('nuevo/', Nuevo_Accion.as_view(), name='nuevo'),
    path('mostrar/', Mostrar_Caja.as_view(), name='mostrar'),
    path('filtrar/', Filtrar_Caja.as_view(), name='filtrar'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import HomeView
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('usuarios.urls', namespace='usuarios')),
    path('prestamos/', include('prestamos.urls', namespace='prestamos')),
    path('ahorros/', include('ahorros.urls', namespace='ahorros')),
    path('acciones/', include('acciones.urls',namespace='acciones')),
    path('caja/', include('caja.urls',namespace='caja')),
    path('inventario/', include('inventario.urls', namespace="inventario")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

prestamos/urls.py
from django.urls import path, re_path

from .views import   Prestamos, mostra_prestamp, GeneratePdf, Inicio, Guardar, Buscar_Prestamo, ListaPrestamos, Prestamo_A_Pagar

from .views import GeneratePdf1
app_name = 'prestamos'

urlpatterns = [
    path("inicio/", Inicio.as_view(), name="inicio"),
    path("guardar/", Guardar, name = "guardar"),
    path("buscar/",Buscar_Prestamo,name="buscar"),
    path('buscar/persona/',ListaPrestamos.as_view()),
    path('buscar/persona/prestamo/', Prestamo_A_Pagar.as_view()),
    path(
        "prestamos/", Prestamos,
        name="prestamos"
    ),
    path("prestamos/mostrar/", mostra_prestamp.as_view()),
    path("pdf1/", GeneratePdf1.as_view(),
         name="pdf1"),
    path("pdf/", GeneratePdf.as_view(),
         name="pdf"),
]

usuarios/urls.py
from django.urls import path

from .views import  LogoutView, UserLoginView, Paso, Libro_Mayor_v, Balance_General_view
from .views import Estado_Resultado_view

app_name = 'usuarios'

urlpatterns = [
    path(
        "login/", UserLoginView.as_view(),
        name="user_login"
    ),
    path(
        "logout/", LogoutView.as_view(),
        name="user_logout"
    ),
    path("profile/", Paso.as_view(),name="Libro Diario"),
    path("libro_mayor", Libro_Mayor_v.as_view(), name='Libro_Mayor'),
    path("balance_general/", Balance_General_view.as_view(),name="Balance_General"),
    path("estado_resultado/", Estado_Resultado_view.as_view(), name="Estado_Resultado"),
]

core/models.py
from django.db import models

# Create your models here.
class Libro_Diario(models.Model):
    Usuario = models.CharField(max_length=50)
    Fecha = models.DateField()
    Descripcion = models.CharField(max_length=100)
    Debe = models.CharField(max_length=150)
    Haber = models.CharField(max_length=150)
    Cuadre = models.FloatField()

class Libro_Mayor(models.Model):
    Cuenta = models.CharField(max_length=50)
    Debe = models.FloatField()
    Haber = models.FloatField()
    Fecha = models.DateField()
    Cuadre = models.FloatField()
    Descripcion = models.CharField(max_length=100)

class Balance_General(models.Model):
    Cuenta = models.CharField(max_length=50)
    Saldo = models.FloatField()
    Activo = models.FloatField()
    Pasivo  = models.FloatField()
    Total = models.FloatField()

class Estado_Resultado(models.Model):
    Cuenta = models.CharField(max_length=50)
    Fecha_1= models.FloatField()
    Fecha_2 = models.FloatField()
    Saldo = models.FloatField()
    Rojo = models.FloatField()
    Amarillo = models.FloatField()
    Verde = models.FloatField()

core/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'core/index.html'

templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="Dummy Banking System" />
        <meta name="author" content="Maksudul Haque" />
        <title>
            {% block head_title %}CACESPROL{% endblock %}
        </title>
        <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">

        {% block head_extra %}{% endblock %}
    </head>
    <body class="bg-gray-100">
        {% block body %}
            {% include 'core/navbar.html' %}
            <div class="lg:container lg:mx-auto">
                {% include 'core/messages.html' %}
                {% block content %}
                <!-- Add content here -->
                {% endblock %}
            </div>
            {% include 'core/footer.html' %}

        {% endblock %}
        {% block footer_extra %}{% endblock %}
    </body>
</html>

templates/core/footer.html
<footer class="footer bg-gray-200 relative pt-1 border-b-2 mt-10">
    <div class="container mx-auto px-6">
        <div class="mt-5 flex flex-col items-center">
            <div class="sm:w-2/3 text-center py-6">
                <p class="text-md text-gray-900 font-bold mb-2">
                    © 2021 by <a href="https://github.com/mcaballeroguillen" target="_blank">Marco A. Caballero</a>
                </p>
            </div>
        </div>
    </div>
</footer>

templates/core/index.html
{% extends 'core/base.html' %}

{% block head_title %}CACESPROL{% endblock %}

{% block content %}
    {% load static %}
    <div class="container mx-auto flex flex-col md:flex-row items-center my-12 md:my-24">
        <!--Left Col-->
        <div class="flex flex-col w-full lg:w-1/2 justify-center items-start pt-12 pb-24 px-6">
            <h1 class="font-bold text-4xl my-4" style="color: #3d8b1c">CACESPROL</h1>
            <div>
            <a href="{% url 'usuarios:user_login' %}" class="bg-transparent hover:bg-gray-800 text-gray-800 hover:text-white rounded shadow hover:shadow-lg py-2 px-4 border border-gray-900 hover:border-transparent" style="background-color: #97cb23; color: white; padding: 10px 20px; border-radius: 5px; text-decoration: none; font-weight: bold;">Entrar</a>
            </div>
        </div>
        <!--Right Col-->
        <div class="w-full lg:w-1/2 lg:py-6 text-center">
            <img src="https://web.upnfm.edu.hn/come/wp-content/uploads/2022/06/CACESPROL-1024x1012.png" alt="logo">
        </div>
    </div>
{% endblock %}

templates/core/messages.html
{% for message in messages %}
<div class="bg-teal-100 border-t-4 border-teal-500 rounded-b text-teal-900 px-4 py-3 shadow-md mt-2" role="alert">
    <div class="flex">
        <div class="py-1"><svg class="fill-current h-6 w-6 text-teal-500 mr-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm12.73-1.41A8 8 0 1 0 4.34 4.34a8 8 0 0 0 11.32 11.32zM9 11V9h2v6H9v-4zm0-6h2v2H9V5z"/></svg></div>
        <div>
            <p class="font-bold">Success!</p>
            <p class="text-sm">{{ message }}</p>
        </div>
    </div>
</div>
{% endfor %}

templates/core/navbar.html
<nav class="flex items-center justify-between flex-wrap bg-gray-800 p-6" style="background-color: darkgreen">
    <div class="flex items-center flex-shrink-0 text-white mr-6">
        <a href="{% url 'usuarios:Libro Diario' %}" class="font-semibold text-xl tracking-tight">Cooperativa</a>
    </div>
    <div class="block lg:hidden">
        <button class="flex items-center px-3 py-2 border rounded text-white border-white-400 hover:text-white hover:border-white">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
        </button>
    </div>
    <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
        {% if request.user.is_authenticated %}
            <div class="text-md lg:flex-grow">
                <a href="{% url 'prestamos:inicio' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                    Préstamos
                </a>
                <a href="{% url 'ahorros:index' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                    Ahorros
                </a>
                <a href="{% url 'acciones:index' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white">
                    Aportaciones &nbsp;&nbsp;&nbsp;
                </a>
            <a href="{% url 'caja:index' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                    Caja
                </a>
                 <a href="{% url 'inventario:index' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white">
                    Inventario &nbsp;&nbsp;&nbsp;
                </a>
                <a href="{% url 'usuarios:Libro_Mayor' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                    Libro Mayor &nbsp;&nbsp;
                </a>
                <a href="{% url 'usuarios:Balance_General' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                    Balance General &nbsp;&nbsp;
                </a>
                 <a href="{% url 'usuarios:Estado_Resultado' %}" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                    Estado de Resultado
                </a>
            </div>
            <div>
                <a href="{% url 'usuarios:user_logout' %}" class="inline-block font-medium text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">Cerrar Sesion</a>
            </div>

        {% else %}
            <div class="text-md lg:flex-grow"></div>
            <div>
                <a href="{% url 'usuarios:user_login' %}" class="mr-2 inline-block font-medium text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">Ingresar</a>
            </div>

        {% endif %}
    </div>
</nav>