caja/urls.py
from django.urls import path, include
from .views import Index, Nuevo_Accion, Mostrar_Caja, Filtrar_Caja

app_name = 'caja'
urlpatterns = [
    path('index/', Index.as_view(), name='index'),
    path('nuevo/', Nuevo_Accion.as_view(), name='nuevo'),
    path('mostrar/', Mostrar_Caja.as_view(), name='mostrar'),
    path('filtrar/', Filtrar_Caja.as_view(), name='filtrar'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import HomeView
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('usuarios.urls', namespace='usuarios')),
    path('prestamos/', include('prestamos.urls', namespace='prestamos')),
    path('ahorros/', include('ahorros.urls', namespace='ahorros')),
    path('acciones/', include('acciones.urls',namespace='acciones')),
    path('caja/', include('caja.urls',namespace='caja')),
    path('inventario/', include('inventario.urls', namespace="inventario")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

prestamos/urls.py
from django.urls import path, re_path

from .views import   Prestamos, mostra_prestamp, GeneratePdf, Inicio, Guardar, Buscar_Prestamo, ListaPrestamos, Prestamo_A_Pagar

from .views import GeneratePdf1
app_name = 'prestamos'

urlpatterns = [
    path("inicio/", Inicio.as_view(), name="inicio"),
    path("guardar/", Guardar, name = "guardar"),
    path("buscar/",Buscar_Prestamo,name="buscar"),
    path('buscar/persona/',ListaPrestamos.as_view()),
    path('buscar/persona/prestamo/', Prestamo_A_Pagar.as_view()),
    path(
        "prestamos/", Prestamos,
        name="prestamos"
    ),
    path("prestamos/mostrar/", mostra_prestamp.as_view()),
    path("pdf1/", GeneratePdf1.as_view(),
         name="pdf1"),
    path("pdf/", GeneratePdf.as_view(),
         name="pdf"),
]

prestamos/models.py
from django.db import models

# Create your models here.


class Datos_prestamos(models.Model):
    id_cliente = models.CharField(max_length=15)
    id_prestamo= models.IntegerField()
    nombre_cliente= models.CharField(max_length=50)
    miembro = models.CharField(max_length=1)
    fecha_otorgado= models.DateField()
    fecha_vencimiento= models.DateField()
    plazo_meses= models.IntegerField()
    taza_mensual= models.FloatField()
    Periodo_Gracia= models.IntegerField()
    Taza_Descuento= models.FloatField()
    Monto = models.FloatField()


class Acciones_Prestamos(models.Model):
    id_prestamo = models.IntegerField()
    num_cuota= models.IntegerField()
    Fecha_Pago= models.DateField()
    Num_recibo= models.IntegerField()
    Monto= models.FloatField()
    Capital = models.FloatField()
    Descuento = models.FloatField()
    Intereses = models.FloatField()
    Pago = models.FloatField()
    Saldo = models.FloatField()
    Saldo_mora = models.FloatField()
    Intereses_moratorios= models.FloatField()

class Temp_Datos_prestamos(models.Model):
    Usuario = models.CharField(max_length=50)
    id_persona = models.CharField(max_length=15)
    nombre_cliente = models.CharField(max_length=50)
    miembro = models.CharField(max_length=1)
    fecha_otorgado = models.DateField()
    plazo_meses = models.IntegerField()
    taza_mensual = models.FloatField()
    Intereses = models.FloatField()
    Periodo_Gracia = models.IntegerField()
    Taza_Descuento = models.FloatField()
    Monto = models.FloatField()


class Temp_Acciones_Prestamos(models.Model):
    Usuario = models.CharField(max_length=50)
    num_cuota = models.IntegerField()
    fecha_cuota = models.DateField()
    capital = models.FloatField()
    Descuento = models.FloatField()
    Intereses = models.FloatField()
    total_cuota = models.FloatField()
    saldo = models.FloatField()

class Variables_Generales(models.Model):
    variable = models.CharField(max_length=50)
    valor = models.CharField(max_length=50)

prestamos/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from datetime import datetime, date
from datetime import timedelta
from core.models import Libro_Diario, Libro_Mayor
from django.views import View
from django.contrib.auth.decorators import login_required, permission_required
from prestamos.models import Temp_Datos_prestamos, Temp_Acciones_Prestamos, Datos_prestamos, Acciones_Prestamos, Variables_Generales
from django.views.generic import TemplateView, RedirectView, ListView
# Create your views here.
from prestamos.utils import render_to_pdf
from caja.models import Caja


def Prestamos(request):


    if request.method=="POST":
        if validacion_datos(request):
            Temp_Datos_prestamos.objects.all().delete()
            Temp_Acciones_Prestamos.objects.all().delete()
            generar_prestamo(request)
            return  redirect("mostrar/")



    LA = Variables_Generales.objects.filter(variable="Interes_mora").count()

    if LA==0:
        A = Variables_Generales(
            variable="Interes_mora",
            valor = "0.001"
        )
        A.save()

    return  render(request, "transactions/Prestamos.html")


class Inicio(TemplateView):

    template_name='transactions/Index.html'

def validacion_datos(request):


    id = request.POST['Identidad']
    if len(id) != 13:
        messages.error(request, "Error en Identidad", "Debe medir 13")
        return False
    plazo = request.POST['Plazo']
    s = str(plazo)
    if s.isdigit()==False:
        messages.error(request,"Error, plazo no correcto")
        return False
    else:
        if int(plazo)<=0:
            messages.error(request,"Plazo debe ser mayor que 0")
            return False
    taza = request.POST['Interes']
    s = str(taza)
    if s.isdigit()==False:
        messages.error(request,"Error en Taza de intereses")
        return False
    else:
        if float(taza)<0 or float(taza)>100:
            messages.error(request,"Error en taza de interes")
            return False
    gracia = request.POST['Periodo de Gracia']
    s=str(gracia)
    if s.isdigit()==False:
        messages.error(request,"Error en Periodo de Gracia")
        return False
    else:
        if int(gracia)<0 or int(gracia)>=int(plazo):
            messages.error(request,"Error en Periodo de Gracia")
            return False

    monto = request.POST["Monto"]
    s= str(monto)
    if s.isdigit()==False:
        messages.error(request,"Error en monto")
        return False
    else:

        ahorros = Libro_Mayor.objects.filter(Cuenta="Capital_e_intereses_en_ahorros").last().Cuadre
        caja = Libro_Mayor.objects.filter(Cuenta="Caja").last().Cuadre
        techo =(ahorros*0.3)*-1

        if float(monto)<0:
            messages.error(request,"Error en monto")
            return False
        else:
            sobrante= caja-float(monto)
            if sobrante<=0 or sobrante<techo:
                messages.error(request,"No se puede prestar esa cantidad")
                return False

    descuento= request.POST['Descuento']
    s=str(descuento)
    if s.isdigit()==False:
        messages.error(request,"Errro en Descuento")
        return False
    else:
        if float(descuento)<0 or float(descuento)> float(monto):
            messages.error(request, "Errro en Descuento")
            return False


    FO = request.POST['Fecha Otorgado']
    FO = datetime.strptime(FO,"%Y-%m-%d").date()
    FP = request.POST['Fecha Primera Cuota']
    FP = datetime.strptime(FP,"%Y-%m-%d").date()
    delta= FP-FO
    dias = int(delta.days)
    if dias<30:
        messages.error(request, "Error Fecha de Pago de Primera Cuota ", "Debe medir 13")
        return False
    return  True


def generar_prestamo(request):

    Tanual= float(request.POST['Interes'])/100
    Tmensual = float(Tanual)/12
    monto = float(request.POST['Monto'])
    num_cuotas = int(request.POST['Plazo'])
    Interese = generar_cuotas(request)

    temp = Temp_Datos_prestamos(
        Usuario= request.user.username,
        id_persona=request.POST['Identidad'],
        nombre_cliente=request.POST['Cliente'],
        miembro=request.POST['Miembro'],
        fecha_otorgado=datetime.strptime(request.POST['Fecha Otorgado'],"%Y-%m-%d").date(),
        plazo_meses= int(request.POST['Plazo']),
        taza_mensual= Tmensual,
        Periodo_Gracia= int(request.POST['Periodo de Gracia']),
        Taza_Descuento= float(request.POST['Descuento']),
        Intereses=Interese,
        Monto= float(request.POST['Monto']),


    )
    temp.save()



def generar_cuotas(request):
    monto = float(request.POST['Monto'])
    Taza_anual = float(request.POST['Interes'])
    Taza_anual=Taza_anual/100
    Taza_mensual=(Taza_anual/12)
    num_cuotas = int(request.POST['Plazo'])
    pe_gracia = int(request.POST['Periodo de Gracia'])
    cuotas_validas= num_cuotas-pe_gracia
    capital_mensual= round(monto/cuotas_validas,2)
    fecha_1 = request.POST['Fecha Primera Cuota']
    fecha_1= datetime.strptime(fecha_1,"%Y-%m-%d").date()
    saldo = monto
    descuento = float(request.POST['Descuento'])
    interes_total=0
    for x in range(num_cuotas):
        interes = round(saldo*Taza_mensual,2)
        capital_cuota= capital_mensual
        if x+1<= pe_gracia:
            capital_cuota=0
        fecha_cuota = fecha_1+ timedelta(days=30*x)
        saldo = round(saldo - capital_cuota, 2)
        cuota = Temp_Acciones_Prestamos(
            Usuario=request.user.username,
            num_cuota=x+1,
            fecha_cuota=fecha_cuota,
            Descuento=0,
            capital= round(capital_cuota,2),
            Intereses= round(interes,2),
            total_cuota= round(capital_cuota+interes,2),
            saldo=round(saldo,2)

        )

        interes_total=interes_total+interes
        cuota.save()
    num_c = num_cuotas
    while descuento >0:
        cuota = Temp_Acciones_Prestamos.objects.get(num_cuota=num_c)
        capital_cuota= cuota.capital
        interes = cuota.Intereses
        saldo = cuota.saldo
        total_cuota=0
        delta = capital_cuota-descuento
        new_capital=0
        des_aplicado=0
        if delta<0:
            descuento=descuento-capital_cuota
            des_aplicado=capital_cuota
        else:
            new_capital=delta
            des_aplicado=capital_cuota-delta
            new_saldo=saldo-delta
            descuento=0

        total_cuota = new_capital + interes
        #cuota.capital=round(new_capital,2)
        cuota.total_cuota=round(total_cuota,2)
        cuota.Descuento=round(des_aplicado,2)
        cuota.save()
        num_c=num_c-1

    return  interes_total



class mostra_prestamp(ListView):
    template_name = 'transactions/Prestamos_mostrar.html'
    model = Temp_Acciones_Prestamos

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        info= Temp_Datos_prestamos.objects.filter(Usuario=self.request.user.username)
        prest= info[0]
        context.update({
            'Cliente': prest.nombre_cliente,
            'Identidad': prest.id_persona,
            'Fecha_O': prest.fecha_otorgado,
            'Plazo': (prest.plazo_meses),
            'Tanual': (prest.taza_mensual*12)*100,
            'Tmensual': (prest.taza_mensual)*100,
            'Pgracia': prest.Periodo_Gracia,
            'Descuento': prest.Taza_Descuento,
            'Monto':prest.Monto,
            'Intereses': prest.Intereses,

            'Mora': float(Variables_Generales.objects.get(variable="Interes_mora").valor)*1000

        })
        return  context

    def get_queryset(self):
        return Temp_Acciones_Prestamos.objects.filter(Usuario=self.request.user.username)


class GeneratePdf(View):
    def get(self, request, *args, **kwargs):
        info = Temp_Datos_prestamos.objects.filter(Usuario=request.user.username)
        prest = info[0]
        lista= Temp_Acciones_Prestamos.objects.filter(Usuario=request.user.username)
        context={
            'Cliente': prest.nombre_cliente,
            'Identidad': prest.id_persona,
            'Fecha_O': prest.fecha_otorgado,
            'Plazo': prest.plazo_meses,
            'Tanual': prest.taza_mensual * 12,
            'Tmensual': prest.taza_mensual,
            'Pgracia': prest.Periodo_Gracia,
            'Descuento': prest.Taza_Descuento,
            'Monto': prest.Monto,
            'Intereses': prest.Intereses,
            'object_list': lista,
            'Mora': Variables_Generales.objects.get(variable="Interes_mora").valor

        }
        pdf = render_to_pdf('pdf/prestamo_pdf.html', context)
        if pdf:
            response = HttpResponse(pdf, content_type='prestamos/pdf')
            filename = "Prestamo_%s.pdf" % (prest.nombre_cliente)
            content = "inline; filename=%s" % (filename)
            download = request.GET.get("download")
            if download:
                content = "attachment; filename=%s" % (filename)
            response['Content-Disposition'] = content
            return response
        return HttpResponse("Not found")



def Guardar(request):
    num_prestamos = Datos_prestamos.objects.all().count()
    id_presta = num_prestamos + 1
    info = Temp_Datos_prestamos.objects.filter(Usuario=request.user.username)
    prest = info[0]
    ahorros = Libro_Mayor.objects.filter(Cuenta="Capital_e_intereses_en_ahorros").last().Cuadre
    caja = Libro_Mayor.objects.filter(Cuenta="Caja").last().Cuadre
    techo = (ahorros * 0.3) * -1
    sobrante = caja - float(prest.Monto)
    if sobrante <= 0 or sobrante < techo:
            messages.error(request, "No se puede prestar esa cantidad, no hay dinero suficiente en caja")
            return render(request,'transactions/Prestamos_mostrar.html')

    coutas = Temp_Acciones_Prestamos.objects.filter(Usuario=request.user.username)
    num_cuota = int(prest.plazo_meses)
    desc= Temp_Acciones_Prestamos.Descuento

templates/transactions/Balance_General.html
{% extends 'core/base.html' %}

{% block head_title %}Balance General{% endblock %}



{% block content %}
    <h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10">Balance General</h1>
    <hr />

    <table class="table-auto mx-auto w-full mt-8">
        <thead class="bg-gray-800 text-white">
        <tr class="uppercase font-semibold text-sm">
            <th class="px-4 py-2">Cuenta</th>
            <th class="px-4 py-2">Saldo</th>
            <th class="px-4 py-2"> Activo</th>
            <th class="px-4 py-2"> Pasivo</th>
            <th class="px-4 py-2"> Capital Contable</th>

        </tr>
        </thead>
        <tbody>
        {% for transaction in object_list %}
        <tr class="{% cycle 'bg-gray-300' 'bg-white-100' %}">
            <td class="border px-4 py-2 text-center">{{ transaction.Cuenta }}</td>
            <td class="border px-4 py-2 text-center">{{ transaction.Saldo }}</td>
            <td class="border px-4 py-2 text-center">{{ transaction.Activo }}</td>
            <td class="border px-4 py-2 text-center">{{ transaction.Pasivo }}</td>
            <td class="border px-4 py-2 text-center">{{ transaction.Total }}</td>

        </tr>
        {% endfor %}

        </tbody>
    </table>
{% endblock %}

templates/transactions/Buscar_Prestamos.html
{% extends 'core/base.html' %}

{% block head_title %}Nuevo Préstamo{% endblock %}



{% block content %}
    <h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10">Buscar  Préstamo</h1>
    <hr />
    <form method="POST" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}

        <div class="mb-4">
             <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                Identidad
            </label>
            <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="Identidad" id="Identidad"  required placeholder="Identidad del Cliente">
        </div>
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
            Buscar
        </button>
    </form>

{% endblock %}

templates/transactions/Index.html
{% extends 'core/base.html' %}

{% block head_title %}Nuevo Préstamo{% endblock %}



{% block content %}
    <h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10"> Préstamos </h1>
    <hr />
<center>
   <a href="{% url 'prestamos:prestamos' %}"class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Nuevo
   </a>
    <a href="{% url 'prestamos:buscar' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Existente
   </a>
</center>
{% endblock %}

templates/transactions/Mostra A Pagar.html
{% extends 'core/base.html' %}

{% block head_title %}Nuevo Préstamo{% endblock %}



{% block content %}
    <h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10"> Préstamo {{ Id_Prestamo }}</h1>
    <hr />

        <div class="mb-4">
            <label class="block text-gray-700 text-sm" for="amount">
                <b>Cliente</b>: {{Cliente}}
            </label>
            <label class="block text-gray-700 text-sm" for="amount">
                <b>Identidad</b>: {{ Identidad }}
            </label>
            <label class="block text-gray-700 text-sm" for="amount">
                <b>Fecha Otorgado</b>: {{ Fecha_O }}
            </label>

            <label class="block text-gray-700 text-sm" for="amount">
                <b>Plazo en Meses</b>: {{ Plazo }}
            </label>

            <label class="block text-gray-700 text-sm" for="amount">
               <b>Taza de Interes Anual</b>: {{ Tanual }}
            </label>

            <label class="block text-gray-700 text-sm" for="amount">
                <b>Taza de Interes Mensual</b>: {{ Tmensual }}
            </label>

            <label class="block text-gray-700 text-sm" for="amount">
                <b>Periodo de Gracia</b>: {{ Pgracia }}
            </label>

            <label class="block text-gray-700 text-sm" for="amount">
               <b>Tasa de Descuento</b>: {{ Descuento }}
            </label>

            <label class="block text-gray-700 text-sm" for="amount">
               <b>Monto</b>: {{ Monto }}
            </label>
            <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
               Recago por Mora: {{ Mora }}
            </label>
        </div>
        {% if messages %}
            <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
         <a href="{% url 'prestamos:pdf1' %}"class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Imprimir
         </a>

    <form method="POST" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}

        <div class="mb-4">

            <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                Monto
            </label>
            <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="Monto" id="Monto"  required placeholder="Monto a Pagar">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                Número de Recibo
            </label>
            <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="Recibo" id="Recibo"  required placeholder="Recibo de Pago">
        </div>
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
            Pagar
        </button>
    </form>
    <table class="table-auto mx-auto w-full mt-8">
        <thead class="bg-gray-800 text-white">
        <tr class="uppercase font-semibold text-sm">
            <th class="px-4 py-2">Núm</th>
            <th class="px-4 py-2">Fecha de Pago</th>
            <th class="px-4 py-2">Núm Recibo</th>
            <th class="px-4 py-2">Capital</th>
            <th class="px-4 py-2">Descuento</th>
            <th class="px-4 py-2">Intereses </th>
            <th class="px-4 py-2">Intereses Moratorios </th>
            <th class="px-4 py-2">Total Cuota</th>
            <th class="px-4 py-2">Saldo</th>
             <th class="px-4 py-2">Saldo en Mora</th>
            <th class="px-4 py-2">Pago</th>
        </tr>
        </thead>
        <tbody>
        {% for transaction in object_list %}
        <tr class="{% cycle 'bg-gray-300' 'bg-white-100' %}">
            <td class="border px-4 py-2 text-center">{{ transaction.num_cuota }}</td>
            <td class="border px-4 py-2 text-center">{{ transaction.Fecha_Pago }}</td>
            <td class="border px-4 py-2 text-center">{{ transaction.Num_recibo }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Capital }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Descuento }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Intereses }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Intereses_moratorios }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Monto }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Saldo }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Saldo_mora }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Pago }}</td>
        </tr>
        {% endfor %}

        </tbody>
    </table>
{% endblock %}

templates/transactions/Prestamos_mostrar.html
{% extends 'core/base.html' %}

{% block head_title %}Nuevo Préstamo{% endblock %}



{% block content %}
    <h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10">Nuevo Préstamo</h1>
    <hr />

        <div class="mb-4">
            <label class="block text-gray-700 text-sm for="amount">
                <b>Cliente</b>: {{Cliente}}
            </label>
            <label class="block text-gray-700 text-sm for="amount">
                <b>Identidad</b>: {{ Identidad }}
            </label>
            <label class="block text-gray-700 text-sm for="amount">
                <b>Fecha Otorgado</b>: {{ Fecha_O }}
            </label>

            <label class="block text-gray-700 text-sm for="amount">
                <b>Plazo en Meses</b>: {{ Plazo }}
            </label>

            <label class="block text-gray-700 text-sm for="amount">
             <b>   Taza de Interes Anual</b>: {{ Tanual }}
            </label>

            <label class="block text-gray-700 text-sm for="amount">
             <b>   Taza de Interes Mensual</b>: {{ Tmensual }}
            </label>

            <label class="block text-gray-700 text-sm for="amount">
             <b>   Periodo de Gracia</b>: {{ Pgracia }}
            </label>

            <label class="block text-gray-700 text-sm for="amount">
             <b>  Tasa de Descuento</b>: {{ Descuento }}
            </label>

            <label class="block text-gray-700 text-sm for="amount">
            <b>   Monto</b>: {{ Monto }}
            </label>
            <label class="block text-gray-700 text-sm for="amount">
             <b>  Recago por Mora</b>: {{ Mora }}
            </label>
        </div>
        {% if messages %}
            <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
         <a href="{% url 'prestamos:pdf' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Imprimir
         </a>
        <a href="{% url 'prestamos:guardar' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Guardar
         </a>
        <button onclick="Atrás()" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Atrás</button>
        <script>
        function Atrás() {
            window.history.back();
        }
</script>
    <table class="table-auto mx-auto w-full mt-8">
        <thead class="bg-gray-800 text-white">
        <tr class="uppercase font-semibold text-sm">
            <th class="px-4 py-2">Núm Cuota</th>
            <th class="px-4 py-2">Fecha de Pago</th>
            <th class="px-4 py-2">Capital</th>
            <th class="px-4 py-2">Descuento</th>
            <th class="px-4 py-2">Intereses</th>
            <th class="px-4 py-2">Total Cuota</th>
            <th class="px-4 py-2">Saldo</th>
        </tr>
        </thead>
        <tbody>
        {% for transaction in object_list %}
        <tr class="{% cycle 'bg-gray-300' 'bg-white-100' %}">
            <td class="border px-4 py-2 text-center">{{ transaction.num_cuota }}</td>
            <td class="border px-4 py-2 text-center">{{ transaction.fecha_cuota }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.capital }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Descuento }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.Intereses }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.total_cuota }}</td>
            <td class="border px-4 py-2 text-center">L {{ transaction.saldo }}</td>
        </tr>
        {% endfor %}
        <tr class="bg-gray-600 text-white">
            <th class="px-4 py-2 text-right" colspan="2"> Total</th>
            <th class="px-4 py-2 text-center">L {{ Monto }}</th>
            <th class="px-4 py-2 text-right" colspan="1"> Total</th>
            <th class="px-4 py-2 text-center">L {{ Intereses }}</th>
        </tr>
        </tbody>
    </table>
{% endblock %}

templates/transactions/transaction_form.html
{% extends 'core/base.html' %}

{% block head_title %}{{ title }}{% endblock %}

{% block content %}
<h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10">{{ title }}</h1>
<hr />
<div class="w-full mt-5">
    <form method="post" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}

        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                Amount
            </label>
            <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="amount" id="amount" type="number" required placeholder="Amount">
        </div>
        {% if form.amount.errors %}
            {% for error in form.amount.errors %}
                <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
            {% endfor %}
        {% endif %}
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
            Submit
        </button>
    </form>
</div>
{% endblock %}